name: Enhancment
description: Contribute to Plugin through Pull Request
title: ""
labels: [enhancement]
assignees: 'donavanbecker'
body:
  - type: markdown
    attributes:
      value: |
        Is your enhancement related to a problem? Please describe.
  - type: input
    attributes:
      label: Problem
      placeholder: A clear and concise description of what the problem is. Ex. I am always frustrated when [...] 
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Describe the solution you are addding.    
  - type: input
    attributes:
      label: Solution
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Describe alternatives you've considered.   
  - type: input
    attributes:
      label: Alternatives
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: input
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here. Post devicediscovery logs here.
    validations:
      required: false