name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Workflow Changes'
    labels:
      - 'workflow'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Updated Dependencies'
    labels:
      - 'dependencies'
  - title: 'Documentation'
    labels:
      - 'docs'

change-template: '- $TITLE @$AUTHOR [#$NUMBER]'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES