blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Rainbird
    url: https://discord.gg/peABghgtaV
    about: Please ask and answer questions here.
  - name: Homebridge-Rainbrid - Pull Requests
    url: https://github.com/donavanbecker/homebridge-rainbird/pulls
    about: Please report security vulnerabilities here.
